# Generated by Django 4.1.7 on 2023-03-31 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_alter_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 10, 4, 0, 945156, tzinfo=datetime.timezone.utc)),
        ),
    ]
